/*
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.formance.ledgerclient.model;

import com.formance.ledgerclient.model.Transaction;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for ListTransactions200ResponseCursorAllOf
 */
public class ListTransactions200ResponseCursorAllOfTest {
    private final ListTransactions200ResponseCursorAllOf model = new ListTransactions200ResponseCursorAllOf();

    /**
     * Model tests for ListTransactions200ResponseCursorAllOf
     */
    @Test
    public void testListTransactions200ResponseCursorAllOf() {
        // TODO: test ListTransactions200ResponseCursorAllOf
    }

    /**
     * Test the property 'data'
     */
    @Test
    public void dataTest() {
        // TODO: test data
    }

}
