/*
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.formance.ledgerclient.model;

import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import org.junit.Assert;
import org.junit.Ignore;
import org.junit.Test;


/**
 * Model tests for Script
 */
public class ScriptTest {
    private final Script model = new Script();

    /**
     * Model tests for Script
     */
    @Test
    public void testScript() {
        // TODO: test Script
    }

    /**
     * Test the property 'plain'
     */
    @Test
    public void plainTest() {
        // TODO: test plain
    }

    /**
     * Test the property 'vars'
     */
    @Test
    public void varsTest() {
        // TODO: test vars
    }

}
