/*
 * Ledger API
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.4.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.formance.ledgerclient.model;

import java.util.Objects;
import java.util.Arrays;
import com.formance.ledgerclient.model.Posting;
import com.formance.ledgerclient.model.Volume;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.time.OffsetDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * Transaction
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-07-11T13:01:27.855198Z[Etc/UTC]")
public class Transaction {
  public static final String SERIALIZED_NAME_POSTINGS = "postings";
  @SerializedName(SERIALIZED_NAME_POSTINGS)
  private List<Posting> postings = new ArrayList<>();

  public static final String SERIALIZED_NAME_REFERENCE = "reference";
  @SerializedName(SERIALIZED_NAME_REFERENCE)
  private String reference;

  public static final String SERIALIZED_NAME_METADATA = "metadata";
  @SerializedName(SERIALIZED_NAME_METADATA)
  private Map<String, Object> metadata = null;

  public static final String SERIALIZED_NAME_TIMESTAMP = "timestamp";
  @SerializedName(SERIALIZED_NAME_TIMESTAMP)
  private OffsetDateTime timestamp;

  public static final String SERIALIZED_NAME_TXID = "txid";
  @SerializedName(SERIALIZED_NAME_TXID)
  private Integer txid;

  public static final String SERIALIZED_NAME_PRE_COMMIT_VOLUMES = "preCommitVolumes";
  @SerializedName(SERIALIZED_NAME_PRE_COMMIT_VOLUMES)
  private Map<String, Map<String, Volume>> preCommitVolumes = null;

  public static final String SERIALIZED_NAME_POST_COMMIT_VOLUMES = "postCommitVolumes";
  @SerializedName(SERIALIZED_NAME_POST_COMMIT_VOLUMES)
  private Map<String, Map<String, Volume>> postCommitVolumes = null;

  public Transaction() { 
  }

  public Transaction postings(List<Posting> postings) {
    
    this.postings = postings;
    return this;
  }

  public Transaction addPostingsItem(Posting postingsItem) {
    this.postings.add(postingsItem);
    return this;
  }

   /**
   * Get postings
   * @return postings
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public List<Posting> getPostings() {
    return postings;
  }


  public void setPostings(List<Posting> postings) {
    this.postings = postings;
  }


  public Transaction reference(String reference) {
    
    this.reference = reference;
    return this;
  }

   /**
   * Get reference
   * @return reference
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "ref:001", value = "")

  public String getReference() {
    return reference;
  }


  public void setReference(String reference) {
    this.reference = reference;
  }


  public Transaction metadata(Map<String, Object> metadata) {
    
    this.metadata = metadata;
    return this;
  }

  public Transaction putMetadataItem(String key, Object metadataItem) {
    if (this.metadata == null) {
      this.metadata = new HashMap<>();
    }
    this.metadata.put(key, metadataItem);
    return this;
  }

   /**
   * Get metadata
   * @return metadata
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"admin\":true,\"a\":{\"nested\":{\"key\":\"value\"}}}", value = "")

  public Map<String, Object> getMetadata() {
    return metadata;
  }


  public void setMetadata(Map<String, Object> metadata) {
    this.metadata = metadata;
  }


  public Transaction timestamp(OffsetDateTime timestamp) {
    
    this.timestamp = timestamp;
    return this;
  }

   /**
   * Get timestamp
   * @return timestamp
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public OffsetDateTime getTimestamp() {
    return timestamp;
  }


  public void setTimestamp(OffsetDateTime timestamp) {
    this.timestamp = timestamp;
  }


  public Transaction txid(Integer txid) {
    
    this.txid = txid;
    return this;
  }

   /**
   * Get txid
   * @return txid
  **/
  @javax.annotation.Nonnull
  @ApiModelProperty(required = true, value = "")

  public Integer getTxid() {
    return txid;
  }


  public void setTxid(Integer txid) {
    this.txid = txid;
  }


  public Transaction preCommitVolumes(Map<String, Map<String, Volume>> preCommitVolumes) {
    
    this.preCommitVolumes = preCommitVolumes;
    return this;
  }

  public Transaction putPreCommitVolumesItem(String key, Map<String, Volume> preCommitVolumesItem) {
    if (this.preCommitVolumes == null) {
      this.preCommitVolumes = new HashMap<>();
    }
    this.preCommitVolumes.put(key, preCommitVolumesItem);
    return this;
  }

   /**
   * Get preCommitVolumes
   * @return preCommitVolumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"orders:1\":{\"USD\":{\"input\":100,\"output\":10,\"balance\":90}},\"orders:2\":{\"USD\":{\"input\":100,\"output\":10,\"balance\":90}}}", value = "")

  public Map<String, Map<String, Volume>> getPreCommitVolumes() {
    return preCommitVolumes;
  }


  public void setPreCommitVolumes(Map<String, Map<String, Volume>> preCommitVolumes) {
    this.preCommitVolumes = preCommitVolumes;
  }


  public Transaction postCommitVolumes(Map<String, Map<String, Volume>> postCommitVolumes) {
    
    this.postCommitVolumes = postCommitVolumes;
    return this;
  }

  public Transaction putPostCommitVolumesItem(String key, Map<String, Volume> postCommitVolumesItem) {
    if (this.postCommitVolumes == null) {
      this.postCommitVolumes = new HashMap<>();
    }
    this.postCommitVolumes.put(key, postCommitVolumesItem);
    return this;
  }

   /**
   * Get postCommitVolumes
   * @return postCommitVolumes
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(example = "{\"orders:1\":{\"USD\":{\"input\":100,\"output\":10,\"balance\":90}},\"orders:2\":{\"USD\":{\"input\":100,\"output\":10,\"balance\":90}}}", value = "")

  public Map<String, Map<String, Volume>> getPostCommitVolumes() {
    return postCommitVolumes;
  }


  public void setPostCommitVolumes(Map<String, Map<String, Volume>> postCommitVolumes) {
    this.postCommitVolumes = postCommitVolumes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    Transaction transaction = (Transaction) o;
    return Objects.equals(this.postings, transaction.postings) &&
        Objects.equals(this.reference, transaction.reference) &&
        Objects.equals(this.metadata, transaction.metadata) &&
        Objects.equals(this.timestamp, transaction.timestamp) &&
        Objects.equals(this.txid, transaction.txid) &&
        Objects.equals(this.preCommitVolumes, transaction.preCommitVolumes) &&
        Objects.equals(this.postCommitVolumes, transaction.postCommitVolumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(postings, reference, metadata, timestamp, txid, preCommitVolumes, postCommitVolumes);
  }

  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class Transaction {\n");
    sb.append("    postings: ").append(toIndentedString(postings)).append("\n");
    sb.append("    reference: ").append(toIndentedString(reference)).append("\n");
    sb.append("    metadata: ").append(toIndentedString(metadata)).append("\n");
    sb.append("    timestamp: ").append(toIndentedString(timestamp)).append("\n");
    sb.append("    txid: ").append(toIndentedString(txid)).append("\n");
    sb.append("    preCommitVolumes: ").append(toIndentedString(preCommitVolumes)).append("\n");
    sb.append("    postCommitVolumes: ").append(toIndentedString(postCommitVolumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

